#!/usr/bin/env bash
# Displays contents of file /etc/passwd

while read -r l
do
	paste -d: <(echo "$l" | cut -d ":" -f1) <(echo "$l" | cut -d ":" -f4) <(echo "$l" | cut -d ":" -f6)
done < "/etc/passwd"
