#!/usr/bin/env bash
# Displays "Best School" 10 times, but for the 9th iteration, displays Best School and then Hi on a new line
n=0
while ((n < 10))
do
	echo "Best School"
	if ((n == 8))
	then
		echo "Hi"
	fi
	((n++))
done
