#!/usr/bin/env bash
# Displays "bad luck" for the 4th loop iteration, "good luck" for the 8th and "Best School" for the other iterations

n=1
while ((n <= 10))
do
	if ((n == 4))
	then
		echo "bad luck"
	elif ((n == 8))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((n++))
done
