#!/usr/bin/env bash
# Displays hours from 0 to 12, and minutes from 1 to 59

hour=0
while ((hour <= 12))
do
	min=1
	echo "Hour: $hour"
	while ((min <= 59))
	do
		echo "$min"
		((min++))
	done
	((hour++))
done
